#ifndef sheet_h_fhasdufhqweioq34ryh8iouertgfhouiaerfghiouerwfghuio
#define sheet_h_fhasdufhqweioq34ryh8iouertgfhouiaerfghiouerwfghuio
namespace Pikachu
{
	struct NetL
	{
		enum regular
		{
			_id_ = 1,
			_integer_ = 2,
			_realC_ = 3,
			_string_ = 4,
			_header_ = 5,
			_include_ = 6,
			_forward_ = 7,
			_backward_ = 8,
			_Hv_ = 9,
			_gradient_ = 10,
			_demo_ = 11,
			_print_ = 12,
			_sum_ = 13,
			_func_ = 14,
			_net_ = 15,
			_tensor_ = 16,
			_def_ = 17,
			_input_ = 18,
			_output_ = 19,
			_para_ = 20,
			_return_ = 21,
			_for_ = 22,
			_if_ = 23,
			_else_ = 24,
			_real_ = 25,
			_complex_ = 26,
			_sint_ = 27,
			_uint_ = 28,
			_bool_ = 29,
			_sin_ = 30,
			_cos_ = 31,
			_exp_ = 32,
			_ln_ = 33,
			_log_ = 34,
			_sqrt_ = 35,
			_pow_ = 36,
			_spaces_ = 37,
			_enters_ = 38,
			_tab_ = 39,
			_semicolon_ = 40,
			_colon_ = 41,
			_dot_ = 42,
			_comma_ = 43,
			_braceL_ = 44,
			_braceR_ = 45,
			_left_ = 46,
			_right_ = 47,
			_squareL_ = 48,
			_squareR_ = 49,
			_angleL_ = 50,
			_angleR_ = 51,
			_anntationS_ = 52,
			_anntationM_ = 53,
			_multi_ = 54,
			_div_ = 55,
			_sub_ = 56,
			_add_ = 57,
			_assign_ = 58
		};
		enum group
		{
			_id___ = 1,
			_number___ = 2,
			_string___ = 3,
			_macro___ = 4,
			_instructG___ = 5,
			_instructN___ = 6,
			_reserved___ = 7,
			_type___ = 8,
			_function1___ = 9,
			_function2___ = 10,
			_format___ = 11,
			_division___ = 12,
			_braket___ = 13,
			_anntation___ = 14,
			_operatmd___ = 15,
			_operatas___ = 16,
			_assignments___ = 17
		};
		static int next(int state, const char c);
		static int action(int state);
		static int GroupGet(int state);
	};
	struct NetG
	{
		enum type
		{
			accept = 0,
			error = 1,
			push = 2,
			reduce = 3
		};
		enum rules
		{
			all_all_ = 0,
			context_defs_ = 1,
			//<DEF*>_first_ = 2,
			//<DEF*>_multi_ = 3,
			DEF_symbolic_ = 4,
			DEF_network_ = 5,
			DEF_def_ = 6,
			DEF_exp_ = 7,
			DEF_diff_ = 8,
			OPERATOR_operatmd_ = 9,
			OPERATOR_operatas_ = 10,
			//[operatmd]_multi_ = 11,
			//[operatmd]_div_ = 12,
			//[operatas]_sub_ = 13,
			//[operatas]_add_ = 14,
			DIFF_NET_diff_ = 15,
			DIFF_NET_diff2_ = 16,
			DIFF_NET_demo_ = 17,
			DIFF_NET_print_ = 18,
			//[instructG]_forward_ = 19,
			//[instructG]_backward_ = 20,
			//[instructG]_Hv_ = 21,
			//[instructG]_gradient_ = 22,
			//[instructG]_demo_ = 23,
			//[instructG]_print_ = 24,
			ID_LISTSQUARE_ID_LISTSQUARE_ = 25,
			ID_LIST_single_ = 26,
			ID_LIST_multi_ = 27,
			EXP_RIGHT_default_ = 28,
			EXP_RIGHT_add_ = 29,
			EXP_MUL_default_ = 30,
			EXP_MUL_multi_ = 31,
			EXP_MINUS_default_ = 32,
			EXP_MINUS_plus_ = 33,
			UNIT_id_ = 34,
			UNIT_call_ = 35,
			UNIT_const_ = 36,
			UNIT_complex_ = 37,
			//[number]_integer_ = 38,
			//[number]_realC_ = 39,
			ID_array_ = 40,
			ID_single_ = 41,
			INDEX_COMPUTE_single_ = 42,
			CALL_call_1_ = 43,
			CALL_call_2_ = 44,
			//[function1]_sin_ = 45,
			//[function1]_cos_ = 46,
			//[function1]_exp_ = 47,
			//[function1]_ln_ = 48,
			//[function1]_log_ = 49,
			//[function1]_sqrt_ = 50,
			//[function2]_pow_ = 51,
			SYMBOLIC_SYMBOLIC_ = 52,
			PARA_PARA_ = 53,
			//<SYMBOLICPARAS>_single_ = 54,
			//<SYMBOLICPARAS>_multi_ = 55,
			SYMBOLICPARA_input_ = 56,
			SYMBOLICPARA_para_ = 57,
			SYMBOLICPARA_output_ = 58,
			SYMBOLICBODY_SYMBOLICBODY_ = 59,
			//<STATEMENT*>_first_ = 60,
			//<STATEMENT*>_multi_ = 61,
			STATEMENT_const_ = 62,
			STATEMENT_def1_ = 63,
			STATEMENT_def2_ = 64,
			STATEMENT_exp_ = 65,
			CONSTVAR_def1_ = 66,
			CONSTVAR_def2_ = 67,
			//[type]_real_ = 68,
			//[type]_complex_ = 69,
			//[type]_sint_ = 70,
			//[type]_uint_ = 71,
			//[type]_bool_ = 72,
			VALUE_single_ = 73,
			VALUE_multi_ = 74,
			VALUELIST_VALUELIST_ = 75,
			VALUES_VALUES_ = 76,
			//<NEXTVALUE*>_first_ = 77,
			//<NEXTVALUE*>_multi_ = 78,
			NEXTVALUE_NEXTVALUE_ = 79,
			NETWORK_NETWORK_ = 80,
			NETBODY_net_ = 81,
			//<NET_STATEMENT*>_first_ = 82,
			//<NET_STATEMENT*>_multi_ = 83,
			NET_STATEMENT_const_ = 84,
			NET_STATEMENT_exp_ = 85,
			NET_STATEMENT_def_ = 86,
			NET_STATEMENT_tensorDef1_ = 87,
			NET_STATEMENT_tensorDef2_ = 88,
			TENSORID_TENSORID_ = 89,
			TENSOR_TENSOR_ = 90,
			INDEXLIST_INDEXLIST_ = 91,
			INDEXUNITS_null_ = 92,
			INDEXUNITS_single_ = 93,
			INDEXUNITS_multi_ = 94,
			ID2_yes_ = 95,
			ID2_no_ = 96,
			TENSORVALUE_single_ = 97,
			TENSORVALUE_single1_ = 98,
			TENSORVALUE_multi_ = 99,
			TENSORVALUE_singleF_ = 100,
			TENSORVALUE_multiF_ = 101,
			SUMSYMBOL_single_ = 102,
			SUMSYMBOL_multi_ = 103,
			SQ_INDEXUNITS_single_ = 104
		};
		enum nonterminal
		{
			_all_ = 0,
			_context_ = 1,
			//_<DEF*>_ = 2,
			_DEF_ = 3,
			_OPERATOR_ = 4,
			//_[operatmd]_ = 5,
			//_[operatas]_ = 6,
			_DIFF_NET_ = 7,
			//_[instructG]_ = 8,
			_ID_LISTSQUARE_ = 9,
			_ID_LIST_ = 10,
			_EXP_RIGHT_ = 11,
			_EXP_MUL_ = 12,
			_EXP_MINUS_ = 13,
			_UNIT_ = 14,
			//_[number]_ = 15,
			_ID_ = 16,
			_INDEX_COMPUTE_ = 17,
			_CALL_ = 18,
			//_[function1]_ = 19,
			//_[function2]_ = 20,
			_SYMBOLIC_ = 21,
			_PARA_ = 22,
			//_<SYMBOLICPARAS>_ = 23,
			_SYMBOLICPARA_ = 24,
			_SYMBOLICBODY_ = 25,
			//_<STATEMENT*>_ = 26,
			_STATEMENT_ = 27,
			_CONSTVAR_ = 28,
			//_[type]_ = 29,
			_VALUE_ = 30,
			_VALUELIST_ = 31,
			_VALUES_ = 32,
			//_<NEXTVALUE*>_ = 33,
			_NEXTVALUE_ = 34,
			_NETWORK_ = 35,
			_NETBODY_ = 36,
			//_<NET_STATEMENT*>_ = 37,
			_NET_STATEMENT_ = 38,
			_TENSORID_ = 39,
			_TENSOR_ = 40,
			_INDEXLIST_ = 41,
			_INDEXUNITS_ = 42,
			_ID2_ = 43,
			_TENSORVALUE_ = 44,
			_SUMSYMBOL_ = 45,
			_SQ_INDEXUNITS_ = 46
		};
		static const size_t StateCount;
		static const size_t NonTerminalCount;
		static const size_t TerminalCount;
		static const size_t RulesCount;
		static const int GOTO[206][47];
		static const int ACTION[206][59];
		static const int RulesToSymbol[105];
		static const int RulesLength[105];
		static const char* const RulesName[105];
		static const int Implicit[105];
	};
	struct NetPreL
	{
		enum regular
		{
			_id_ = 1,
			_integer_ = 2,
			_realC_ = 3,
			_string_ = 4,
			_header_ = 5,
			_include_ = 6,
			_forward_ = 7,
			_backward_ = 8,
			_Hv_ = 9,
			_gradient_ = 10,
			_demo_ = 11,
			_print_ = 12,
			_sum_ = 13,
			_func_ = 14,
			_net_ = 15,
			_tensor_ = 16,
			_def_ = 17,
			_input_ = 18,
			_output_ = 19,
			_para_ = 20,
			_return_ = 21,
			_for_ = 22,
			_if_ = 23,
			_else_ = 24,
			_real_ = 25,
			_complex_ = 26,
			_sint_ = 27,
			_uint_ = 28,
			_bool_ = 29,
			_sin_ = 30,
			_cos_ = 31,
			_exp_ = 32,
			_ln_ = 33,
			_log_ = 34,
			_sqrt_ = 35,
			_pow_ = 36,
			_spaces_ = 37,
			_enters_ = 38,
			_tab_ = 39,
			_semicolon_ = 40,
			_colon_ = 41,
			_dot_ = 42,
			_comma_ = 43,
			_braceL_ = 44,
			_braceR_ = 45,
			_left_ = 46,
			_right_ = 47,
			_squareL_ = 48,
			_squareR_ = 49,
			_angleL_ = 50,
			_angleR_ = 51,
			_anntationS_ = 52,
			_anntationM_ = 53,
			_multi_ = 54,
			_div_ = 55,
			_sub_ = 56,
			_add_ = 57,
			_assign_ = 58
		};
		enum group
		{
			_id___ = 1,
			_number___ = 2,
			_string___ = 3,
			_macro___ = 4,
			_instructG___ = 5,
			_instructN___ = 6,
			_reserved___ = 7,
			_type___ = 8,
			_function1___ = 9,
			_function2___ = 10,
			_format___ = 11,
			_division___ = 12,
			_braket___ = 13,
			_anntation___ = 14,
			_operatmd___ = 15,
			_operatas___ = 16,
			_assignments___ = 17
		};
		static int next(int state, const char c);
		static int action(int state);
		static int GroupGet(int state);
	};
	struct NetPreG
	{
		enum type
		{
			accept = 0,
			error = 1,
			push = 2,
			reduce = 3
		};
		enum rules
		{
			all_all_ = 0,
			pretreat_meow_ = 1,
			//<DEF*>_first_ = 2,
			//<DEF*>_multi_ = 3,
			DEF_anntation_ = 4,
			DEF_anything_ = 5,
			DEF_include_ = 6,
			//[anntation]_anntationS_ = 7,
			//[anntation]_anntationM_ = 8,
			INCLUDE_include_ = 9,
			INCLUDE_include2_ = 10,
			MACRO_single_ = 11,
			MACRO_multi_ = 12,
			ANY_identifier_ = 13,
			ANY_number_ = 14,
			ANY_string_ = 15,
			ANY_instructG_ = 16,
			ANY_instructN_ = 17,
			ANY_reserved_ = 18,
			ANY_type_ = 19,
			ANY_function1_ = 20,
			ANY_function2_ = 21,
			ANY_format_ = 22,
			ANY_division_ = 23,
			ANY_braket_ = 24,
			ANY_operatmd_ = 25,
			ANY_operatas_ = 26,
			ANY_assignments_ = 27,
			//[id]_id_ = 28,
			//[number]_integer_ = 29,
			//[number]_realC_ = 30,
			//[instructG]_forward_ = 31,
			//[instructG]_backward_ = 32,
			//[instructG]_Hv_ = 33,
			//[instructG]_gradient_ = 34,
			//[instructG]_demo_ = 35,
			//[instructG]_print_ = 36,
			//[instructN]_sum_ = 37,
			//[reserved]_func_ = 38,
			//[reserved]_net_ = 39,
			//[reserved]_tensor_ = 40,
			//[reserved]_def_ = 41,
			//[reserved]_input_ = 42,
			//[reserved]_output_ = 43,
			//[reserved]_para_ = 44,
			//[reserved]_return_ = 45,
			//[reserved]_for_ = 46,
			//[reserved]_if_ = 47,
			//[reserved]_else_ = 48,
			//[type]_real_ = 49,
			//[type]_complex_ = 50,
			//[type]_sint_ = 51,
			//[type]_uint_ = 52,
			//[type]_bool_ = 53,
			//[function1]_sin_ = 54,
			//[function1]_cos_ = 55,
			//[function1]_exp_ = 56,
			//[function1]_ln_ = 57,
			//[function1]_log_ = 58,
			//[function1]_sqrt_ = 59,
			//[function2]_pow_ = 60,
			//[format]_spaces_ = 61,
			//[format]_enters_ = 62,
			//[format]_tab_ = 63,
			//[division]_semicolon_ = 64,
			//[division]_colon_ = 65,
			//[division]_dot_ = 66,
			//[division]_comma_ = 67,
			//[braket]_braceL_ = 68,
			//[braket]_braceR_ = 69,
			//[braket]_left_ = 70,
			//[braket]_right_ = 71,
			//[braket]_squareL_ = 72,
			//[braket]_squareR_ = 73,
			//[braket]_angleL_ = 74,
			//[braket]_angleR_ = 75,
			//[operatmd]_multi_ = 76,
			//[operatmd]_div_ = 77,
			//[operatas]_sub_ = 78,
			//[operatas]_add_ = 79,
			//[assignments]_assign_ = 80
		};
		enum nonterminal
		{
			_all_ = 0,
			_pretreat_ = 1,
			//_<DEF*>_ = 2,
			_DEF_ = 3,
			//_[anntation]_ = 4,
			_INCLUDE_ = 5,
			_MACRO_ = 6,
			_ANY_ = 7,
			//_[id]_ = 8,
			//_[number]_ = 9,
			//_[instructG]_ = 10,
			//_[instructN]_ = 11,
			//_[reserved]_ = 12,
			//_[type]_ = 13,
			//_[function1]_ = 14,
			//_[function2]_ = 15,
			//_[format]_ = 16,
			//_[division]_ = 17,
			//_[braket]_ = 18,
			//_[operatmd]_ = 19,
			//_[operatas]_ = 20,
			//_[assignments]_ = 21
		};
		static const size_t StateCount;
		static const size_t NonTerminalCount;
		static const size_t TerminalCount;
		static const size_t RulesCount;
		static const int GOTO[82][22];
		static const int ACTION[82][59];
		static const int RulesToSymbol[81];
		static const int RulesLength[81];
		static const char* const RulesName[81];
		static const int Implicit[81];
	};



}



#endif // 