#ifndef sheet_h_fhasdufhqweioq34ryh8iouertgfhouiaerfghiouerwfghuio
#define sheet_h_fhasdufhqweioq34ryh8iouertgfhouiaerfghiouerwfghuio
namespace Pikachu
{
	struct NetL
	{
		enum regular
		{
			_id_ = 1,
			_integer_ = 2,
			_realC_ = 3,
			_string_ = 4,
			_header_ = 5,
			_include_ = 6,
			_sum_ = 7,
			_func_ = 8,
			_net_ = 9,
			_tensor_ = 10,
			_def_ = 11,
			_input_ = 12,
			_output_ = 13,
			_para_ = 14,
			_return_ = 15,
			_for_ = 16,
			_if_ = 17,
			_else_ = 18,
			_real_ = 19,
			_complex_ = 20,
			_sint_ = 21,
			_uint_ = 22,
			_bool_ = 23,
			_sin_ = 24,
			_cos_ = 25,
			_exp_ = 26,
			_ln_ = 27,
			_log_ = 28,
			_sqrt_ = 29,
			_pow_ = 30,
			_spaces_ = 31,
			_enters_ = 32,
			_tab_ = 33,
			_semicolon_ = 34,
			_colon_ = 35,
			_dot_ = 36,
			_comma_ = 37,
			_braceL_ = 38,
			_braceR_ = 39,
			_left_ = 40,
			_right_ = 41,
			_squareL_ = 42,
			_squareR_ = 43,
			_angleL_ = 44,
			_angleR_ = 45,
			_anntationS_ = 46,
			_anntationM_ = 47,
			_multi_ = 48,
			_div_ = 49,
			_sub_ = 50,
			_add_ = 51,
			_assign_ = 52
		};
		enum group
		{
			_id___ = 1,
			_number___ = 2,
			_string___ = 3,
			_macro___ = 4,
			_instruct___ = 5,
			_reserved___ = 6,
			_type___ = 7,
			_function1___ = 8,
			_function2___ = 9,
			_format___ = 10,
			_division___ = 11,
			_braket___ = 12,
			_anntation___ = 13,
			_operatmd___ = 14,
			_operatas___ = 15,
			_assignments___ = 16
		};
		static int next(int state, const char c);
		static int action(int state);
		static int GroupGet(int state);
	};
	struct NetG
	{
		enum type
		{
			accept = 0,
			error = 1,
			push = 2,
			reduce = 3
		};
		enum rules
		{
			all_all_ = 0,
			context_defs_ = 1,
			//<DEF*>_first_ = 2,
			//<DEF*>_multi_ = 3,
			DEF_symbolic_ = 4,
			DEF_network_ = 5,
			DEF_def_ = 6,
			DEF_diff_ = 7,
			OPERATOR_operatmd_ = 8,
			OPERATOR_operatas_ = 9,
			//[operatmd]_multi_ = 10,
			//[operatmd]_div_ = 11,
			//[operatas]_sub_ = 12,
			//[operatas]_add_ = 13,
			DIFF_NET_diff_ = 14,
			//EXP_RIGHT_<implicit>_ = 15,
			EXP_RIGHT_add_ = 16,
			//EXP_MUL_<implicit>_ = 17,
			EXP_MUL_multi_ = 18,
			//EXP_MINUS_<implicit>_ = 19,
			EXP_MINUS_plus_ = 20,
			UNIT_id_ = 21,
			UNIT_call_ = 22,
			UNIT_const_ = 23,
			UNIT_complex_ = 24,
			//[number]_integer_ = 25,
			//[number]_realC_ = 26,
			ID_array_ = 27,
			ID_single_ = 28,
			INDEX_COMPUTE_single_ = 29,
			CALL_call_1_ = 30,
			CALL_call_2_ = 31,
			//[function1]_sin_ = 32,
			//[function1]_cos_ = 33,
			//[function1]_exp_ = 34,
			//[function1]_ln_ = 35,
			//[function1]_log_ = 36,
			//[function1]_sqrt_ = 37,
			//[function2]_pow_ = 38,
			SYMBOLIC_SYMBOLIC_ = 39,
			PARA_PARA_ = 40,
			//<SYMBOLICPARAS>_single_ = 41,
			//<SYMBOLICPARAS>_multi_ = 42,
			SYMBOLICPARA_input_ = 43,
			SYMBOLICPARA_para_ = 44,
			SYMBOLICPARA_output_ = 45,
			SYMBOLICBODY_SYMBOLICBODY_ = 46,
			//<STATEMENT*>_first_ = 47,
			//<STATEMENT*>_multi_ = 48,
			STATEMENT_def_ = 49,
			STATEMENT_exp_ = 50,
			EXPRESSION_EXPRESSION_ = 51,
			VAR_def1_ = 52,
			VAR_def2_ = 53,
			DEF_VAR_const_ = 54,
			DEF_VAR_var_ = 55,
			//[type]_real_ = 56,
			//[type]_complex_ = 57,
			//[type]_sint_ = 58,
			//[type]_uint_ = 59,
			//[type]_bool_ = 60,
			VALUE_single_ = 61,
			VALUE_multi_ = 62,
			VALUELIST_VALUELIST_ = 63,
			VALUES_VALUES_ = 64,
			//<NEXTVALUE*>_first_ = 65,
			//<NEXTVALUE*>_multi_ = 66,
			NEXTVALUE_NEXTVALUE_ = 67,
			NETWORK_NETWORK_ = 68,
			NETBODY_net_ = 69,
			//<NET_STATEMENT*>_first_ = 70,
			//<NET_STATEMENT*>_multi_ = 71,
			NET_STATEMENT_const_ = 72,
			NET_STATEMENT_exp_ = 73,
			NET_STATEMENT_def_ = 74,
			NET_STATEMENT_def2_ = 75,
			NET_STATEMENT_tensorDef1_ = 76,
			NET_STATEMENT_tensorDef2_ = 77,
			CONSTVAR_def1_ = 78,
			CONSTVAR_def2_ = 79,
			TENSORID_TENSORID_ = 80,
			TENSOR_TENSOR_ = 81,
			INDEXLIST_INDEXLIST_ = 82,
			INDEXUNITS_single_ = 83,
			INDEXUNITS_multi_ = 84,
			ID2_yes_ = 85,
			ID2_no_ = 86,
			TENSORVALUE_single_ = 87,
			TENSORVALUE_multi_ = 88,
			TENSORVALUE_singleF_ = 89,
			TENSORVALUE_multiF_ = 90,
			SUMSYMBOL_single_ = 91,
			SUMSYMBOL_multi_ = 92,
			SQ_INDEXUNITS_single_ = 93
		};
		enum nonterminal
		{
			_all_ = 0,
			_context_ = 1,
			//_<DEF*>_ = 2,
			_DEF_ = 3,
			_OPERATOR_ = 4,
			//_[operatmd]_ = 5,
			//_[operatas]_ = 6,
			_DIFF_NET_ = 7,
			_EXP_RIGHT_ = 8,
			_EXP_MUL_ = 9,
			_EXP_MINUS_ = 10,
			_UNIT_ = 11,
			//_[number]_ = 12,
			_ID_ = 13,
			_INDEX_COMPUTE_ = 14,
			_CALL_ = 15,
			//_[function1]_ = 16,
			//_[function2]_ = 17,
			_SYMBOLIC_ = 18,
			_PARA_ = 19,
			//_<SYMBOLICPARAS>_ = 20,
			_SYMBOLICPARA_ = 21,
			_SYMBOLICBODY_ = 22,
			//_<STATEMENT*>_ = 23,
			_STATEMENT_ = 24,
			_EXPRESSION_ = 25,
			_VAR_ = 26,
			_DEF_VAR_ = 27,
			//_[type]_ = 28,
			_VALUE_ = 29,
			_VALUELIST_ = 30,
			_VALUES_ = 31,
			//_<NEXTVALUE*>_ = 32,
			_NEXTVALUE_ = 33,
			_NETWORK_ = 34,
			_NETBODY_ = 35,
			//_<NET_STATEMENT*>_ = 36,
			_NET_STATEMENT_ = 37,
			_CONSTVAR_ = 38,
			_TENSORID_ = 39,
			_TENSOR_ = 40,
			_INDEXLIST_ = 41,
			_INDEXUNITS_ = 42,
			_ID2_ = 43,
			_TENSORVALUE_ = 44,
			_SUMSYMBOL_ = 45,
			_SQ_INDEXUNITS_ = 46
		};
		static const size_t StateCount;
		static const size_t NonTerminalCount;
		static const size_t TerminalCount;
		static const size_t RulesCount;
		static const int GOTO[175][47];
		static const int ACTION[175][53];
		static const int RulesToSymbol[94];
		static const int RulesLength[94];
		static const char* const RulesName[94];
		static const int Implicit[94];
	};
	struct NetPreL
	{
		enum regular
		{
			_id_ = 1,
			_integer_ = 2,
			_realC_ = 3,
			_string_ = 4,
			_header_ = 5,
			_include_ = 6,
			_sum_ = 7,
			_func_ = 8,
			_net_ = 9,
			_tensor_ = 10,
			_def_ = 11,
			_input_ = 12,
			_output_ = 13,
			_para_ = 14,
			_return_ = 15,
			_for_ = 16,
			_if_ = 17,
			_else_ = 18,
			_real_ = 19,
			_complex_ = 20,
			_sint_ = 21,
			_uint_ = 22,
			_bool_ = 23,
			_sin_ = 24,
			_cos_ = 25,
			_exp_ = 26,
			_ln_ = 27,
			_log_ = 28,
			_sqrt_ = 29,
			_pow_ = 30,
			_spaces_ = 31,
			_enters_ = 32,
			_tab_ = 33,
			_semicolon_ = 34,
			_colon_ = 35,
			_dot_ = 36,
			_comma_ = 37,
			_braceL_ = 38,
			_braceR_ = 39,
			_left_ = 40,
			_right_ = 41,
			_squareL_ = 42,
			_squareR_ = 43,
			_angleL_ = 44,
			_angleR_ = 45,
			_anntationS_ = 46,
			_anntationM_ = 47,
			_multi_ = 48,
			_div_ = 49,
			_sub_ = 50,
			_add_ = 51,
			_assign_ = 52
		};
		enum group
		{
			_id___ = 1,
			_number___ = 2,
			_string___ = 3,
			_macro___ = 4,
			_instruct___ = 5,
			_reserved___ = 6,
			_type___ = 7,
			_function1___ = 8,
			_function2___ = 9,
			_format___ = 10,
			_division___ = 11,
			_braket___ = 12,
			_anntation___ = 13,
			_operatmd___ = 14,
			_operatas___ = 15,
			_assignments___ = 16
		};
		static int next(int state, const char c);
		static int action(int state);
		static int GroupGet(int state);
	};

	struct NetPreG
	{
		enum type
		{
			accept = 0,
			error = 1,
			push = 2,
			reduce = 3
		};
		enum rules
		{
			all_all_ = 0,
			pretreat_meow_ = 1,
			//<DEF*>_first_ = 2,
			//<DEF*>_multi_ = 3,
			DEF_anntation_ = 4,
			DEF_anything_ = 5,
			DEF_include_ = 6,
			//[anntation]_anntationS_ = 7,
			//[anntation]_anntationM_ = 8,
			INCLUDE_include_ = 9,
			INCLUDE_include2_ = 10,
			MACRO_single_ = 11,
			MACRO_multi_ = 12,
			ANY_identifier_ = 13,
			ANY_number_ = 14,
			ANY_string_ = 15,
			ANY_instruct_ = 16,
			ANY_reserved_ = 17,
			ANY_type_ = 18,
			ANY_function1_ = 19,
			ANY_function2_ = 20,
			ANY_format_ = 21,
			ANY_division_ = 22,
			ANY_braket_ = 23,
			ANY_operatmd_ = 24,
			ANY_operatas_ = 25,
			ANY_assignments_ = 26,
			//[id]_id_ = 27,
			//[number]_integer_ = 28,
			//[number]_realC_ = 29,
			//[instruct]_sum_ = 30,
			//[reserved]_func_ = 31,
			//[reserved]_net_ = 32,
			//[reserved]_tensor_ = 33,
			//[reserved]_def_ = 34,
			//[reserved]_input_ = 35,
			//[reserved]_output_ = 36,
			//[reserved]_para_ = 37,
			//[reserved]_return_ = 38,
			//[reserved]_for_ = 39,
			//[reserved]_if_ = 40,
			//[reserved]_else_ = 41,
			//[type]_real_ = 42,
			//[type]_complex_ = 43,
			//[type]_sint_ = 44,
			//[type]_uint_ = 45,
			//[type]_bool_ = 46,
			//[function1]_sin_ = 47,
			//[function1]_cos_ = 48,
			//[function1]_exp_ = 49,
			//[function1]_ln_ = 50,
			//[function1]_log_ = 51,
			//[function1]_sqrt_ = 52,
			//[function2]_pow_ = 53,
			//[format]_spaces_ = 54,
			//[format]_enters_ = 55,
			//[format]_tab_ = 56,
			//[division]_semicolon_ = 57,
			//[division]_colon_ = 58,
			//[division]_dot_ = 59,
			//[division]_comma_ = 60,
			//[braket]_braceL_ = 61,
			//[braket]_braceR_ = 62,
			//[braket]_left_ = 63,
			//[braket]_right_ = 64,
			//[braket]_squareL_ = 65,
			//[braket]_squareR_ = 66,
			//[braket]_angleL_ = 67,
			//[braket]_angleR_ = 68,
			//[operatmd]_multi_ = 69,
			//[operatmd]_div_ = 70,
			//[operatas]_sub_ = 71,
			//[operatas]_add_ = 72,
			//[assignments]_assign_ = 73
		};
		enum nonterminal
		{
			_all_ = 0,
			_pretreat_ = 1,
			//_<DEF*>_ = 2,
			_DEF_ = 3,
			//_[anntation]_ = 4,
			_INCLUDE_ = 5,
			_MACRO_ = 6,
			_ANY_ = 7,
			//_[id]_ = 8,
			//_[number]_ = 9,
			//_[instruct]_ = 10,
			//_[reserved]_ = 11,
			//_[type]_ = 12,
			//_[function1]_ = 13,
			//_[function2]_ = 14,
			//_[format]_ = 15,
			//_[division]_ = 16,
			//_[braket]_ = 17,
			//_[operatmd]_ = 18,
			//_[operatas]_ = 19,
			//_[assignments]_ = 20
		};
		static const size_t StateCount;
		static const size_t NonTerminalCount;
		static const size_t TerminalCount;
		static const size_t RulesCount;
		static const int GOTO[75][21];
		static const int ACTION[75][53];
		static const int RulesToSymbol[74];
		static const int RulesLength[74];
		static const char* const RulesName[74];
		static const int Implicit[74];
	};
}



#endif // !sheet_h_fhasdufhqweioq34ryh8iouertgfhouiaerfghiouerwfghuio